# Generated by Django 3.1.7 on 2021-03-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peddieforum', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
