# Generated by Django 3.1.7 on 2021-03-07 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peddieforum', '0005_auto_20210307_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='forum_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
