# Generated by Django 3.1.7 on 2021-04-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peddieforum', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
